# Visualizzazione grafica {#sec-vis}

```{r}
#| results: "asis"
#| echo: false
source("_common.R")
```


In questa terza parte del corso,  ci concentreremo sulla visualizzazione dei risultati dell'analisi dell'espressione differenziale,  con particolare attenzione ai geni che abbiamo identificato come differenzialmente espressi.

Esploreremo diverse tecniche di visualizzazione, tra cui:

* **Volcano plot:** Per identificare i geni più significativi e con i maggiori fold change.
* **Heatmap:** Per visualizzare i pattern di espressione di gruppi di geni in diversi campioni.

Attraverso queste visualizzazioni, saremo in grado di:

* **Comunicare i risultati in modo efficace:** Le figure chiare e informative sono essenziali per comunicare i risultati dell'analisi a un pubblico scientifico o non specialistico.
* **Identificare pattern e tendenze:** La visualizzazione grafica può aiutare a identificare pattern e tendenze nei dati che potrebbero non essere evidenti dalle tabelle di numeri.
* **Generare nuove ipotesi:**  La visualizzazione dei risultati può portare a nuove ipotesi e spunti per ulteriori analisi.

Impareremo a creare queste visualizzazioni in R, utilizzando sia le funzioni di base che pacchetti specifici come ggplot2. Sarete in grado di personalizzare le vostre figure per adattarle alle vostre esigenze e al vostro pubblico.

Preparatevi a dare vita ai vostri dati con la potenza della visualizzazione!